<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $year = date('Y');
        $nextyear = $year + 1;
        $array = [
            ['Afghanistan', 'AF', Carbon::create($year, '01', '01')->format('Y/m/d'), Carbon::create($year, '12', '31')->format('Y/m/d'), 85],
            ['Aland Islands', 'AX', Carbon::create($year, '01', '01')->format('Y/m/d'), Carbon::create($year, '12', '31')->format('Y/m/d'), 85],
            ['Albania', 'AL', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Algeria', 'DZ', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['American Samoa', 'AS', Carbon::create($year, '01', '01')->format('Y/m/d'), Carbon::create($year, '12', '31')->format('Y/m/d'), 85],
            ['Andorra', 'AD', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Angola', 'AO', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Anguilla', 'AI', Carbon::create($year, '01', '01')->format('Y/m/d'), Carbon::create($year, '12', '31')->format('Y/m/d'), 85],
            ['Antigua and Barbuda', 'AG', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Argentina', 'AR', Carbon::create($year, '01', '01')->format('Y/m/d'), Carbon::create($year, '12', '31')->format('Y/m/d'), 120],
            ['Armenia', 'AM', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Aruba', 'AW', Carbon::create($year, '01', '01')->format('Y/m/d'), Carbon::create($year, '12', '31')->format('Y/m/d'), 85],
            ['Australia', 'AU', Carbon::create($year, '01', '01')->format('Y/m/d'), Carbon::create($year, '12', '31')->format('Y/m/d'), 85],
            ['Austria', 'AT', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Azerbaijan', 'AZ', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Bahamas', 'BS', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Bahrain', 'BH', Carbon::create($year, '01', '01')->format('Y/m/d'), Carbon::create($year, '12', '31')->format('Y/m/d'), 85],
            ['Bangladesh', 'BD', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Barbados', 'BB', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Belarus', 'BY', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Belgium', 'BE', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Belize', 'BZ', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Benin', 'BJ', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Bermuda', 'BM', Carbon::create($year, '01', '01')->format('Y/m/d'), Carbon::create($year, '12', '31')->format('Y/m/d'), 85],
            ['Bhutan', 'BT', Carbon::create($year, '01', '01')->format('Y/m/d'), Carbon::create($year, '12', '31')->format('Y/m/d'), 85],
            ['Bolivia', 'BO', Carbon::create($year, '01', '01')->format('Y/m/d'), Carbon::create($year, '12', '31')->format('Y/m/d'), 85],
            ['Bosnia and Herzegovina', 'BA', Carbon::create($year, '01', '01')->format('Y/m/d'), Carbon::create($year, '12', '31')->format('Y/m/d'), 85],
            ['Botswana', 'BW', Carbon::create($year, '01', '01')->format('Y/m/d'), Carbon::create($year, '12', '31')->format('Y/m/d'), 85],
            ['Brazil', 'BR', Carbon::create($year, '01', '01')->format('Y/m/d'), Carbon::create($year, '12', '31')->format('Y/m/d'), 120],
            ['British Virgin Islands', 'VG', Carbon::create($year, '01', '01')->format('Y/m/d'), Carbon::create($year, '12', '31')->format('Y/m/d'), 85],
            ['Brunei Darussalam', 'BN', Carbon::create($year, '01', '01')->format('Y/m/d'), Carbon::create($year, '12', '31')->format('Y/m/d'), 85],
            ['Bulgaria', 'BG', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Burkina Faso', 'BF', Carbon::create($year, '01', '01')->format('Y/m/d'), Carbon::create($year, '12', '31')->format('Y/m/d'), 85],
            ['Burundi', 'BI', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Cambodia', 'KH', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Cameroon', 'CM', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Canada', 'CA', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Cape Verde', 'CV', Carbon::create($year, '01', '01')->format('Y/m/d'), Carbon::create($year, '12', '31')->format('Y/m/d'), 85],
            ['Cayman Islands', 'KY', Carbon::create($year, '01', '01')->format('Y/m/d'), Carbon::create($year, '12', '31')->format('Y/m/d'), 85],
            ['Central African Republic', 'CF', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Chad', 'TD', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Chile', 'CL', Carbon::create($year, '01', '01')->format('Y/m/d'), Carbon::create($year, '12', '31')->format('Y/m/d'), 85],
            ['China', 'CN', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Hong Kong', 'HK', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Macao', 'MO', Carbon::create($year, '01', '01')->format('Y/m/d'), Carbon::create($year, '12', '31')->format('Y/m/d'), 85],
            ['Colombia', 'CO', Carbon::create($year, '01', '01')->format('Y/m/d'), Carbon::create($year, '12', '31')->format('Y/m/d'), 85],
            ['Comoros', 'KM', Carbon::create($year, '01', '01')->format('Y/m/d'), Carbon::create($year, '12', '31')->format('Y/m/d'), 85],
            ['Congo', 'CG', Carbon::create($year, '01', '01')->format('Y/m/d'), Carbon::create($year, '12', '31')->format('Y/m/d'), 85],
            ['Cook Islands', 'CK', Carbon::create($year, '01', '01')->format('Y/m/d'), Carbon::create($year, '12', '31')->format('Y/m/d'), 85],
            ['Democratic Republic of the Congo', 'CD', Carbon::create($year, '01', '01')->format('Y/m/d'), Carbon::create($year, '12', '31')->format('Y/m/d'), 85],
            ['Costa Rica', 'CR', Carbon::create($year, '01', '01')->format('Y/m/d'), Carbon::create($year, '12', '31')->format('Y/m/d'), 85],
            ['Cote Ivoire', '', Carbon::create($year, '01', '01')->format('Y/m/d'), Carbon::create($year, '12', '31')->format('Y/m/d'), 85],
            ['Croatia', 'HR', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Cuba', 'CU', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Cyprus', 'CY', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Czech Republic', 'CZ', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['North Korea', 'KP', Carbon::create($year, '01', '01')->format('Y/m/d'), Carbon::create($year, '12', '31')->format('Y/m/d'), 85],
            ['Denmark', 'DK', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Djibouti', 'DJ', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Dominica', 'DM', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Dominican Republic', 'DO', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Ecuador', 'EC', Carbon::create($year, '01', '01')->format('Y/m/d'), Carbon::create($year, '12', '31')->format('Y/m/d'), 85],
            ['Egypt', 'EG', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['El Salvador', 'SV', Carbon::create($year, '01', '01')->format('Y/m/d'), Carbon::create($year, '12', '31')->format('Y/m/d'), 85],
            ['Equatorial Guinea', '', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Eritrea', 'ER', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Estonia', 'EE', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Ethiopia', 'ET', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Faeroe Islands', 'FO', Carbon::create($year, '01', '01')->format('Y/m/d'), Carbon::create($year, '12', '31')->format('Y/m/d'), 85],
            ['Falkland Islands', 'FK', Carbon::create($year, '01', '01')->format('Y/m/d'), Carbon::create($year, '12', '31')->format('Y/m/d'), 85],
            ['Fiji', 'FJ', Carbon::create($year, '01', '01')->format('Y/m/d'), Carbon::create($year, '12', '31')->format('Y/m/d'), 85],
            ['Finland', 'FI', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['France', 'FR', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['French Guiana', 'GF', Carbon::create($year, '01', '01')->format('Y/m/d'), Carbon::create($year, '12', '31')->format('Y/m/d'), 85],
            ['French Polynesia', 'PF', Carbon::create($year, '01', '01')->format('Y/m/d'), Carbon::create($year, '12', '31')->format('Y/m/d'), 85],
            ['Gabon', 'GA', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Gambia', 'GM', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Georgia', 'GE', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Germany', 'DE', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Ghana', 'GH', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Gibraltar', 'GI', Carbon::create($year, '01', '01')->format('Y/m/d'), Carbon::create($year, '12', '31')->format('Y/m/d'), 85],
            ['Greece', 'GR', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Greenland', 'GL', Carbon::create($year, '01', '01')->format('Y/m/d'), Carbon::create($year, '12', '31')->format('Y/m/d'), 85],
            ['Grenada', 'GD', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Guadeloupe', 'GP', Carbon::create($year, '01', '01')->format('Y/m/d'), Carbon::create($year, '12', '31')->format('Y/m/d'), 85],
            ['Guam', 'GU', Carbon::create($year, '01', '01')->format('Y/m/d'), Carbon::create($year, '12', '31')->format('Y/m/d'), 85],
            ['Guatemala', 'GT', Carbon::create($year, '01', '01')->format('Y/m/d'), Carbon::create($year, '12', '31')->format('Y/m/d'), 85],
            ['Guernsey', 'GG', Carbon::create($year, '01', '01')->format('Y/m/d'), Carbon::create($year, '12', '31')->format('Y/m/d'), 85],
            ['Guinea', 'GN', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Guinea-Bissau', 'GW', Carbon::create($year, '01', '01')->format('Y/m/d'), Carbon::create($year, '01', '01')->format('Y/m/d'), 85],
            ['Guyana', 'GY', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Haiti', 'HT', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Holy See', 'VA', Carbon::create($year, '01', '01')->format('Y/m/d'), Carbon::create($year, '12', '31')->format('Y/m/d'), 85],
            ['Honduras', 'HN', Carbon::create($year, '01', '01')->format('Y/m/d'), Carbon::create($year, '12', '31')->format('Y/m/d'), 85],
            ['Hungary', 'HU', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 105],
            ['Iceland', 'IS', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['India', 'IN', Carbon::create($year, '04', '01')->format('Y/m/d'), Carbon::create($nextyear, '03', '31')->format('Y/m/d'), 85],
            ['Indonesia', 'ID', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Iran', 'IR', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Iraq', 'IQ', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Ireland', 'IE', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Isle of Man', 'IM', Carbon::create($year, '01', '01')->format('Y/m/d'), Carbon::create($year, '12', '31')->format('Y/m/d'), 85],
            ['Israel', 'IL', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Italy', 'IT', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Jamaica', 'JM', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Japan', 'JP', Carbon::create($year, '04', '01')->format('Y/m/d'), Carbon::create($nextyear, '03', '31')->format('Y/m/d'), 85],
            ['Jersey', 'JE', Carbon::create($year, '01', '01')->format('Y/m/d'), Carbon::create($year, '12', '31')->format('Y/m/d'), 85],
            ['Jordan', 'JO', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Kazakhstan', 'KZ', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Kenya', 'KE', Carbon::create($year, '01', '01')->format('Y/m/d'), Carbon::create($year, '12', '31')->format('Y/m/d'), 85],
            ['Kiribati', 'KI', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Kuwait', 'KW', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Kyrgyzstan', 'KG', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Laos', 'LA', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Latvia', 'LV', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Lebanon', 'LB', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Lesotho', 'LS', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Liberia', 'LR', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Libyan Arab Jamahiriya', 'LY', Carbon::create($year, '01', '01')->format('Y/m/d'), Carbon::create($year, '12', '31')->format('Y/m/d'), 85],
            ['Liechtenstein', 'LI', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Lithuania', 'LT', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Luxembourg', 'LU', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Madagascar', 'MG', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Malawi', 'MW', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Malaysia', 'MY', Carbon::create($year, '01', '01')->format('Y/m/d'), Carbon::create($year, '12', '31')->format('Y/m/d'), 85],
            ['Maldives', 'MV', Carbon::create($year, '01', '01')->format('Y/m/d'), Carbon::create($year, '12', '31')->format('Y/m/d'), 85],
            ['Mali', 'ML', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Malta', 'MT', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Marshall Islands', 'MH', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Martinique', 'MQ', Carbon::create($year, '01', '01')->format('Y/m/d'), Carbon::create($year, '12', '31')->format('Y/m/d'), 85],
            ['Mauritania', 'MR', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Mauritius', 'MU', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Mayotte', 'YT', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Mexico', 'MX', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Micronesia', 'FM', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Monaco', 'MC', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Mongolia', 'MN', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Montenegro', 'ME', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Montserrat', 'MS', Carbon::create($year, '01', '01')->format('Y/m/d'), Carbon::create($year, '12', '31')->format('Y/m/d'), 85],
            ['Morocco', 'MA', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Mozambique', 'MZ', Carbon::create($year, '01', '01')->format('Y/m/d'), Carbon::create($year, '12', '31')->format('Y/m/d'), 85],
            ['Myanmar', 'MM', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Namibia', 'NA', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Nauru', 'NR', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Nepal', 'NP', Carbon::create($year, '04', '01')->format('Y/m/d'), Carbon::create($nextyear, '03', '31')->format('Y/m/d'), 85],
            ['Netherlands', 'NL', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Netherlands Antilles', 'AN', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['New Caledonia', 'NC', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['New Zealand', 'NZ', Carbon::create($year, '01', '01')->format('Y/m/d'), Carbon::create($year, '12', '31')->format('Y/m/d'), 85],
            ['Nicaragua', 'NI', Carbon::create($year, '01', '01')->format('Y/m/d'), Carbon::create($year, '12', '31')->format('Y/m/d'), 85],
            ['Niger', 'NE', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Nigeria', 'NG', Carbon::create($year, '01', '01')->format('Y/m/d'), Carbon::create($year, '12', '31')->format('Y/m/d'), 85],
            ['Niue', 'NU', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Norfolk Island', 'NF', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Northern Mariana Islands', 'MP', Carbon::create($year, '01', '01')->format('Y/m/d'), Carbon::create($year, '12', '31')->format('Y/m/d'), 85],
            ['Norway', 'NO', Carbon::create($year, '01', '01')->format('Y/m/d'), Carbon::create($year, '12', '31')->format('Y/m/d'), 85],
            ['Palestine', 'PS', Carbon::create($year, '01', '01')->format('Y/m/d'), Carbon::create($year, '12', '31')->format('Y/m/d'), 85],
            ['Oman', 'OM', Carbon::create($year, '01', '01')->format('Y/m/d'), Carbon::create($year, '12', '31')->format('Y/m/d'), 85],
            ['Pakistan', 'PK', Carbon::create($year, '04', '01')->format('Y/m/d'), Carbon::create($nextyear, '03', '31')->format('Y/m/d'), 85],
            ['Palau', 'PW', Carbon::create($year, '01', '01')->format('Y/m/d'), Carbon::create($year, '12', '31')->format('Y/m/d'), 85],
            ['Panama', 'PA', Carbon::create($year, '01', '01')->format('Y/m/d'), Carbon::create($year, '12', '31')->format('Y/m/d'), 85],
            ['Papua New Guinea', 'PG', Carbon::create($year, '01', '01')->format('Y/m/d'), Carbon::create($year, '12', '31')->format('Y/m/d'), 85],
            ['Paraguay', 'PY', Carbon::create($year, '01', '01')->format('Y/m/d'), Carbon::create($year, '12', '31')->format('Y/m/d'), 85],
            ['Peru', 'PE', Carbon::create($year, '01', '01')->format('Y/m/d'), Carbon::create($year, '12', '31')->format('Y/m/d'), 85],
            ['Philippines', 'PH', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 105],
            ['Pitcairn', 'PN', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Poland', 'PL', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Portugal', 'PT', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Puerto Rico', 'PR', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Qatar', 'QA', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['South Korea', 'KR', Carbon::create($year, '01', '01')->format('Y/m/d'), Carbon::create($year, '12', '31')->format('Y/m/d'), 85],
            ['Moldova', 'MD', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Reunion', 'RE', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Romania', 'RO', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 105],
            ['Russian Federation', 'RU', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Rwanda', 'RW', Carbon::create($year, '01', '01')->format('Y/m/d'), Carbon::create($year, '12', '31')->format('Y/m/d'), 85],
            ['Saint-Barthelemy', 'BL', Carbon::create($year, '01', '01')->format('Y/m/d'), Carbon::create($year, '12', '31')->format('Y/m/d'), 85],
            ['Saint Helena', 'SH', Carbon::create($year, '01', '01')->format('Y/m/d'), Carbon::create($year, '12', '31')->format('Y/m/d'), 85],
            ['Saint Kitts and Nevis', 'KN', Carbon::create($year, '01', '01')->format('Y/m/d'), Carbon::create($year, '12', '31')->format('Y/m/d'), 85],
            ['Saint Lucia', 'LC', Carbon::create($year, '01', '01')->format('Y/m/d'), Carbon::create($year, '12', '31')->format('Y/m/d'), 85],
            ['Saint-Martin', 'MF', Carbon::create($year, '01', '01')->format('Y/m/d'), Carbon::create($year, '12', '31')->format('Y/m/d'), 85],
            ['Saint Pierre and Miquelon', 'PM', Carbon::create($year, '01', '01')->format('Y/m/d'), Carbon::create($year, '12', '31')->format('Y/m/d'), 85],
            ['Saint Vincent and th Grenadines', 'VC', Carbon::create($year, '01', '01')->format('Y/m/d'), Carbon::create($year, '12', '31')->format('Y/m/d'), 85],
            ['Samoa', 'WS', Carbon::create($year, '01', '01')->format('Y/m/d'), Carbon::create($year, '12', '31')->format('Y/m/d'), 85],
            ['San Marino', 'SM', Carbon::create($year, '01', '01')->format('Y/m/d'), Carbon::create($year, '12', '31')->format('Y/m/d'), 85],
            ['Sao Tome and Principe', 'ST', Carbon::create($year, '01', '01')->format('Y/m/d'), Carbon::create($year, '12', '31')->format('Y/m/d'), 85],
            ['Saudi Arabia', 'SA', Carbon::create($year, '01', '01')->format('Y/m/d'), Carbon::create($year, '12', '31')->format('Y/m/d'), 85],
            ['Senegal', 'SN', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Serbia', 'RS', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Seychelles', 'SC', Carbon::create($year, '01', '01')->format('Y/m/d'), Carbon::create($year, '12', '31')->format('Y/m/d'), 85],
            ['Sierra Leone', 'SL', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Singapore', 'SG', Carbon::create($year, '01', '01')->format('Y/m/d'), Carbon::create($year, '12', '31')->format('Y/m/d'), 85],
            ['Slovakia', 'SK', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Slovenia', 'SI', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Solomon Islands', 'SB', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Somalia', 'SO', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['South Africa', 'ZA', Carbon::create($year, '01', '01')->format('Y/m/d'), Carbon::create($year, '12', '31')->format('Y/m/d'), 85],
            ['Spain', 'ES', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Sri Lanka', 'LK', Carbon::create($year, '01', '01')->format('Y/m/d'), Carbon::create($year, '12', '31')->format('Y/m/d'), 85],
            ['Sudan', 'SD', Carbon::create($year, '01', '01')->format('Y/m/d'), Carbon::create($year, '12', '31')->format('Y/m/d'), 85],
            ['Suriname', 'SR', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Svalbard and Jan Maye Islands', 'SJ', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Swaziland', 'SZ', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Sweden', 'SE', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Switzerland', 'CH', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Syrian Arab Republic', 'SY', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Tajikistan', 'TJ', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Thailand', 'TH', Carbon::create($year, '04', '01')->format('Y/m/d'), Carbon::create($nextyear, '03', '31')->format('Y/m/d'), 85],
            ['Macedonia', 'MK', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Timor-Leste', 'TP', Carbon::create($year, '01', '01')->format('Y/m/d'), Carbon::create($year, '12', '31')->format('Y/m/d'), 85],
            ['Togo', 'TG', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Tokelau', 'TK', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Tonga', 'TO', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Trinidad and Tobago', 'TT', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Tunisia', 'TN', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Turkey', 'TR', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Turkmenistan', 'TM', Carbon::create($year, '01', '01')->format('Y/m/d'), Carbon::create($year, '12', '31')->format('Y/m/d'), 85],
            ['Turks and Caicos Islands', 'TC', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Tuvalu', 'TV', Carbon::create($year, '01', '01')->format('Y/m/d'), Carbon::create($year, '12', '31')->format('Y/m/d'), 85],
            ['Uganda', 'UG', Carbon::create($year, '01', '01')->format('Y/m/d'), Carbon::create($year, '12', '31')->format('Y/m/d'), 85],
            ['Ukraine', 'UA', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['United Arab Emirates', 'AE', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['United Kingdom', 'UK', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Tanzania', 'TZ', Carbon::create($year, '04', '01')->format('Y/m/d'), Carbon::create($nextyear, '03', '31')->format('Y/m/d'), 85],
            ['United States', 'US', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 0],
            ['US', 'US', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 0],
            ['U.S. Virgin Islands', 'VI', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Uruguay', 'UY', Carbon::create($year, '01', '01')->format('Y/m/d'), Carbon::create($year, '12', '31')->format('Y/m/d'), 85],
            ['Uzbekistan', 'UZ', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Vanuatu', 'VU', Carbon::create($year, '01', '01')->format('Y/m/d'), Carbon::create($year, '12', '31')->format('Y/m/d'), 85],
            ['Venezuela', 'VE', Carbon::create($year, '01', '01')->format('Y/m/d'), Carbon::create($year, '12', '31')->format('Y/m/d'), 85],
            ['Viet Nam', 'VN', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Wallis and Futuna Islands', 'WF', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Western Sahara', 'EH', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Yemen', 'YE', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
            ['Zambia', 'ZM', Carbon::create($year, '01', '01')->format('Y/m/d'), Carbon::create($year, '12', '31')->format('Y/m/d'), 85],
            ['Zimbabwe', 'ZW', Carbon::create($year, '01', '01')->format('Y/m/d'), Carbon::create($year, '12', '31')->format('Y/m/d'), 85],
            ['South Sudan', 'SS', Carbon::create($year, '08', '01')->format('Y/m/d'), Carbon::create($nextyear, '07', '31')->format('Y/m/d'), 85],
        ];
        foreach ($array as $key => $value) :
            $array2[] = [
                'country'  => $value[0],
                'start_date' => $value[2],
                'end_date' => $value[3],
                'postage_charges' => $value[4],
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ];
        endforeach;

        DB::table('countries')->insert($array2);
    }
}
