<?php

namespace Database\Seeders;
use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $year =date("Y");
        $nextyear=$year+1;
        $array =[
            ['Afghanistan','AF',Carbon::create( $year, '01', '01')->format('Y-m-d'),Carbon::create( $year, '12', '31')->format('Y-m-d'),Carbon::create( $year, '01', '01')->format('Y-m-d')],
            ['Aland Islands','AX',Carbon::create( $year, '01', '01')->format('Y-m-d'),Carbon::create( $year, '12', '31')->format('Y-m-d'),Carbon::create( $year, '01', '01')->format('Y-m-d')],
             ['Albania','AL',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create( $nextyear, '07', '31')->format('Y-m-d')],
             ['Algeria','DZ',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create( $nextyear, '07', '31')->format('Y-m-d')],
            ['American Samoa','AS',Carbon::create( $year, '01', '01')->format('Y-m-d'),Carbon::create( $year, '12', '31')->format('Y-m-d')],
             ['Andorra','AD',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create( $nextyear, '07', '31')->format('Y-m-d')],
             ['Angola','AO',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create( $nextyear, '07', '31')->format('Y-m-d')],
            ['Anguilla','AI',Carbon::create( $year, '01', '01')->format('Y-m-d'),Carbon::create( $year, '12', '31')->format('Y-m-d')],
             ['Antigua and Barbuda','AG',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create( $nextyear, '07', '31')->format('Y-m-d')],
              ['Argentina','AR',Carbon::create( $year, '01', '01')->format('Y-m-d'),Carbon::create( $year, '12', '31')->format('Y-m-d')],
             ['Armenia','AM',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create( $nextyear, '07', '31')->format('Y-m-d')],
            ['Aruba','AW',Carbon::create( $year, '01', '01')->format('Y-m-d'),Carbon::create( $year, '12', '31')->format('Y-m-d')],
             ['Australia','AU',Carbon::create( $year, '01', '01')->format('Y-m-d'),Carbon::create( $year, '12', '31')->format('Y-m-d')],
             ['Austria','AT',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create( $nextyear, '07', '31')->format('Y-m-d')],
             ['Azerbaijan','AZ',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create($nextyear, '07', '31')->format('Y-m-d')],
             ['Bahamas','BS',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create( $nextyear, '07', '31')->format('Y-m-d')],
             ['Bahrain','BH',Carbon::create( $year, '01', '01')->format('Y-m-d'),Carbon::create( $year, '12', '31')->format('Y-m-d')],
             ['Bangladesh','BD',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create( $nextyear, '07', '31')->format('Y-m-d')],
             ['Barbados','BB',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create( $nextyear, '07', '31')->format('Y-m-d')],
             ['Belarus','BY',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create( $nextyear, '07', '31')->format('Y-m-d')],
             ['Belgium','BE',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create( $nextyear, '07', '31')->format('Y-m-d')],
             ['Belize','BZ',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create( $nextyear, '07', '31')->format('Y-m-d')],
             ['Benin','BJ',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create( $nextyear, '07', '31')->format('Y-m-d')],
             ['Bermuda','BM',Carbon::create( $year, '01', '01')->format('Y-m-d'),Carbon::create($year, '12', '31')->format('Y-m-d')],
             ['Bhutan','BT',Carbon::create( $year, '01', '01')->format('Y-m-d'),Carbon::create( $year, '12', '31')->format('Y-m-d')],
             ['Bolivia','BO',Carbon::create( $year, '01', '01')->format('Y-m-d'),Carbon::create( $year, '12', '31')->format('Y-m-d')],
             ['Bosnia and Herzegovina','BA',Carbon::create( $year, '01', '01')->format('Y-m-d'),Carbon::create( $year, '12', '31')->format('Y-m-d')],
             ['Botswana','BW',Carbon::create( $year, '01', '01')->format('Y-m-d'),Carbon::create($year, '12', '31')->format('Y-m-d')],
             ['Brazil','BR',Carbon::create( $year, '01', '01')->format('Y-m-d'),Carbon::create( $year, '12', '31')->format('Y-m-d')],
             ['British Virgin Islands','VG',Carbon::create( $year, '01', '01')->format('Y-m-d'),Carbon::create( $year, '12', '31')->format('Y-m-d')],
             ['Brunei Darussalam','BN',Carbon::create( $year, '01', '01')->format('Y-m-d'),Carbon::create( $year, '12', '31')->format('Y-m-d')],
             ['Bulgaria','BG',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create($nextyear, '07', '31')->format('Y-m-d')],
             ['Burkina Faso','BF',Carbon::create( $year, '01', '01')->format('Y-m-d'),Carbon::create($year, '12', '31')->format('Y-m-d')],
             ['Burundi','BI',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create($nextyear, '07', '31')->format('Y-m-d')],
             ['Cambodia','KH',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create( $nextyear, '07', '31')->format('Y-m-d')],
             ['Cameroon','CM',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create( $nextyear, '07', '31')->format('Y-m-d')],
             ['Canada','CA',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create( $nextyear, '07', '31')->format('Y-m-d')],
             ['Cape Verde','CV',Carbon::create( $year, '01', '01')->format('Y-m-d'),Carbon::create( $year, '12', '31')->format('Y-m-d')],
             ['Cayman Islands','KY',Carbon::create( $year, '01', '01')->format('Y-m-d'),Carbon::create( $year, '12', '31')->format('Y-m-d')],    
             ['Central African Republic','CF',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create($nextyear, '07', '31')->format('Y-m-d')],
             ['Chad','TD',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create( $nextyear, '07', '31')->format('Y-m-d')],
             ['Chile','CL',Carbon::create( $year, '01', '01')->format('Y-m-d'),Carbon::create( $year, '12', '31')->format('Y-m-d')],
             ['China','CN',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create( $nextyear, '07', '31')->format('Y-m-d')],
             ['Hong Kong','HK',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create( $nextyear, '07', '31')->format('Y-m-d')],
            ['Macao','MO',Carbon::create( $year, '01', '01')->format('Y-m-d'),Carbon::create( $year, '12', '31')->format('Y-m-d')],
            ['Colombia','CO',Carbon::create( $year, '01', '01')->format('Y-m-d'),Carbon::create( $year, '12', '31')->format('Y-m-d')],
             ['Comoros','KM',Carbon::create( $year, '01', '01')->format('Y-m-d'),Carbon::create( $year, '12', '31')->format('Y-m-d')],
             ['Congo','CG',Carbon::create( $year, '01', '01')->format('Y-m-d'),Carbon::create( $year, '12', '31')->format('Y-m-d')],
             ['Cook Islands','CK',Carbon::create( $year, '01', '01')->format('Y-m-d'),Carbon::create( $year, '12', '31')->format('Y-m-d')],
             ['Democratic Republic of the Congo','CD',Carbon::create( $year, '01', '01')->format('Y-m-d'),Carbon::create( $year, '12', '31')->format('Y-m-d')],
             ['Costa Rica','CR',Carbon::create( $year, '01', '01')->format('Y-m-d'),Carbon::create( $year, '12', '31')->format('Y-m-d')],
             ['Cote Ivoire','',Carbon::create( $year, '01', '01')->format('Y-m-d'),Carbon::create( $year, '12', '31')->format('Y-m-d')],
             ['Croatia','HR',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create( $nextyear, '07', '31')->format('Y-m-d')],
             ['Cuba','CU',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create( $nextyear, '07', '31')->format('Y-m-d')],
             ['Cyprus','CY',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create( $nextyear, '07', '31')->format('Y-m-d')],
             ['Czech Republic','CZ',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create( $nextyear, '07', '31')->format('Y-m-d')],
             ['North Korea','KP',Carbon::create( $year, '01', '01')->format('Y-m-d'),Carbon::create( $year, '12', '31')->format('Y-m-d')],
             ['Denmark','DK',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create( $nextyear, '07', '31')->format('Y-m-d')],
             ['Djibouti','DJ',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create( $nextyear, '07', '31')->format('Y-m-d')],
             ['Dominica','DM',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create( $nextyear, '07', '31')->format('Y-m-d')],
            ['Dominican Republic','DO',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create( $nextyear, '07', '31')->format('Y-m-d')],
            ['Ecuador','EC',Carbon::create( $year, '01', '01')->format('Y-m-d'),Carbon::create( $year, '12', '31')->format('Y-m-d')],
             ['Egypt','EG',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create($nextyear, '07', '31')->format('Y-m-d')],
             ['El Salvador','SV',Carbon::create( $year, '01', '01')->format('Y-m-d'),Carbon::create( $year, '12', '31')->format('Y-m-d')],
             ['Equatorial Guinea','',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create( $nextyear, '07', '31')->format('Y-m-d')],
             ['Eritrea','ER',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create( $nextyear, '07', '31')->format('Y-m-d')],
             ['Estonia','EE',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create( $nextyear, '07', '31')->format('Y-m-d')],
             ['Ethiopia','ET',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create( $nextyear, '07', '31')->format('Y-m-d')],
             ['Faeroe Islands','FO',Carbon::create( $year, '01', '01')->format('Y-m-d'),Carbon::create( $year, '12', '31')->format('Y-m-d')],
             ['Falkland Islands','FK',Carbon::create( $year, '01', '01')->format('Y-m-d'),Carbon::create( $year, '12', '31')->format('Y-m-d')],
             ['Fiji','FJ',Carbon::create( $year, '01', '01')->format('Y-m-d'),Carbon::create( $year, '12', '31')->format('Y-m-d')],
             ['Finland','FI',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create( $nextyear, '07', '31')->format('Y-m-d')],
             ['France','FR',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create( $nextyear, '07', '31')->format('Y-m-d')],
             ['French Guiana','GF',Carbon::create( $year, '01', '01')->format('Y-m-d'),Carbon::create( $year, '12', '31')->format('Y-m-d')],
             ['French Polynesia','PF',Carbon::create( $year, '01', '01')->format('Y-m-d'),Carbon::create( $year, '12', '31')->format('Y-m-d')],
             ['Gabon','GA',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create( $nextyear, '07', '31')->format('Y-m-d')],
             ['Gambia','GM',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create( $nextyear, '07', '31')->format('Y-m-d')],
             ['Georgia','GE',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create( $nextyear, '07', '31')->format('Y-m-d')],
             ['Germany','DE',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create( $nextyear, '07', '31')->format('Y-m-d')],
             ['Ghana','GH',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create( $nextyear, '07', '31')->format('Y-m-d')],
             ['Gibraltar','GI',Carbon::create( $year, '01', '01')->format('Y-m-d'),Carbon::create($year, '12', '31')->format('Y-m-d')],
             ['Greece','GR',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create( $nextyear, '07', '31')->format('Y-m-d')],
             ['Greenland','GL',Carbon::create( $year, '01', '01')->format('Y-m-d'),Carbon::create( $year, '12', '31')->format('Y-m-d')],
             ['Grenada','GD',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create( $nextyear, '07', '31')->format('Y-m-d')],
             ['Guadeloupe','GP',Carbon::create( $year, '01', '01')->format('Y-m-d'),Carbon::create( $year, '12', '31')->format('Y-m-d')],
             ['Guam','GU',Carbon::create( $year, '01', '01')->format('Y-m-d'),Carbon::create( $year, '12', '31')->format('Y-m-d')],
             ['Guatemala','GT',Carbon::create( $year, '01', '01')->format('Y-m-d'),Carbon::create($year, '12', '31')->format('Y-m-d')],
             ['Guernsey','GG',Carbon::create( $year, '01', '01')->format('Y-m-d'),Carbon::create( $year, '12', '31')->format('Y-m-d')],
             ['Guinea','GN',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create( $nextyear, '07', '31')->format('Y-m-d')],
             ['Guinea-Bissau','GW',Carbon::create( $year, '01', '01')->format('Y-m-d'),Carbon::create( $year, '01', '01')->format('Y-m-d')],
             ['Guyana','GY',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create( $nextyear, '07', '31')->format('Y-m-d')],
             ['Haiti','HT',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create( $nextyear, '07', '31')->format('Y-m-d')],
             ['Holy See','VA',Carbon::create( $year, '01', '01')->format('Y-m-d'),Carbon::create( $year, '12', '31')->format('Y-m-d')],
             ['Honduras','HN',Carbon::create( $year, '01', '01')->format('Y-m-d'),Carbon::create( $year, '12', '31')->format('Y-m-d')],
             ['Hungary','HU',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create( $nextyear, '07', '31')->format('Y-m-d')],
             ['Iceland','IS',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create($nextyear, '07', '31')->format('Y-m-d')],
             ['India','IN',Carbon::create( $year, '04', '01')->format('Y-m-d'),Carbon::create( $nextyear, '03', '31')->format('Y-m-d')],
             ['Indonesia','ID',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create( $nextyear, '07', '31')->format('Y-m-d')],
             ['Iran','IR',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create( $nextyear, '07', '31')->format('Y-m-d')],
             ['Iraq','IQ',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create( $nextyear, '07', '31')->format('Y-m-d')],
             ['Ireland','IE',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create( $nextyear, '07', '31')->format('Y-m-d')],
             ['Isle of Man','IM',Carbon::create( $year, '01', '01')->format('Y-m-d'),Carbon::create( $year, '12', '31')->format('Y-m-d')],
             ['Israel','IL',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create( $nextyear, '07', '31')->format('Y-m-d')],
             ['Italy','IT',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create( $nextyear, '07', '31')->format('Y-m-d')],
             ['Jamaica','JM',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create($nextyear, '07', '31')->format('Y-m-d')],
             ['Japan','JP',Carbon::create( $year, '04', '01')->format('Y-m-d'),Carbon::create( $nextyear, '03', '31')->format('Y-m-d')],
             ['Jersey','JE',Carbon::create( $year, '01', '01')->format('Y-m-d'),Carbon::create( $year, '12', '31')->format('Y-m-d')],
             ['Jordan','JO',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create( $nextyear, '07', '31')->format('Y-m-d')],
            ['Kazakhstan','KZ',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create( $nextyear, '07', '31')->format('Y-m-d')],
            ['Kenya','KE',Carbon::create( $year, '01', '01')->format('Y-m-d'),Carbon::create( $year, '12', '31')->format('Y-m-d')],
            ['Kiribati','KI',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create( $nextyear, '07', '31')->format('Y-m-d')],
            ['Kuwait','KW',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create( $nextyear, '07', '31')->format('Y-m-d')],
            ['Kyrgyzstan','KG',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create( $nextyear, '07', '31')->format('Y-m-d')],
            ['Laos','LA',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create($nextyear, '07', '31')->format('Y-m-d')],
            ['Latvia','LV',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create( $nextyear, '07', '31')->format('Y-m-d')],
            ['Lebanon','LB',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create( $nextyear, '07', '31')->format('Y-m-d')],
            ['Lesotho','LS',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create( $nextyear, '07', '31')->format('Y-m-d')],
            ['Liberia','LR',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create( $nextyear, '07', '31')->format('Y-m-d')],
            ['Libyan Arab Jamahiriya','LY',Carbon::create( $year, '01', '01')->format('Y-m-d'),Carbon::create( $year, '12', '31')->format('Y-m-d')],
            ['Liechtenstein','LI',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create( $nextyear, '07', '31')->format('Y-m-d')],
            ['Lithuania','LT',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create( $nextyear, '07', '31')->format('Y-m-d')],
            ['Luxembourg','LU',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create( $nextyear, '07', '31')->format('Y-m-d')],
            ['Madagascar','MG',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create($nextyear, '07', '31')->format('Y-m-d')],
            ['Malawi','MW',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create( $nextyear, '07', '31')->format('Y-m-d')],
            ['Malaysia','MY',Carbon::create( $year, '01', '01')->format('Y-m-d'),Carbon::create( $year, '12', '31')->format('Y-m-d')],
            ['Maldives','MV',Carbon::create( $year, '01', '01')->format('Y-m-d'),Carbon::create( $year, '12', '31')->format('Y-m-d')],
            ['Mali','ML',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create( $nextyear, '07', '31')->format('Y-m-d')],
            ['Malta','MT',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create($nextyear, '07', '31')->format('Y-m-d')],
            ['Marshall Islands','MH',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create( $nextyear, '07', '31')->format('Y-m-d')],
            ['Martinique','MQ',Carbon::create( $year, '01', '01')->format('Y-m-d'),Carbon::create( $year, '12', '31')->format('Y-m-d')],
            ['Mauritania','MR',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create( $nextyear, '07', '31')->format('Y-m-d')],
            ['Mauritius','MU',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create( $nextyear, '07', '31')->format('Y-m-d')],
            ['Mayotte','YT',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create( $nextyear, '07', '31')->format('Y-m-d')],
            ['Mexico','MX',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create( $nextyear, '07', '31')->format('Y-m-d')],
            ['Micronesia','FM',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create( $nextyear, '07', '31')->format('Y-m-d')],
            ['Monaco','MC',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create( $nextyear, '07', '31')->format('Y-m-d')],
            ['Mongolia','MN',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create( $nextyear, '07', '31')->format('Y-m-d')],
            ['Montenegro','ME',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create( $nextyear, '07', '31')->format('Y-m-d')],
            ['Montserrat','MS',Carbon::create( $year, '01', '01')->format('Y-m-d'),Carbon::create( $year, '12', '31')->format('Y-m-d')],
            ['Morocco','MA',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create( $nextyear, '07', '31')->format('Y-m-d')],
            ['Mozambique','MZ',Carbon::create( $year, '01', '01')->format('Y-m-d'),Carbon::create($year, '12', '31')->format('Y-m-d')],
            ['Myanmar','MM',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create( $nextyear, '07', '31')->format('Y-m-d')],
            ['Namibia','NA',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create( $nextyear, '07', '31')->format('Y-m-d')],
            ['Nauru','NR',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create( $nextyear, '07', '31')->format('Y-m-d')],
            ['Nepal','NP',Carbon::create( $year, '04', '01')->format('Y-m-d'),Carbon::create( $nextyear, '03', '31')->format('Y-m-d')],
            ['Netherlands','NL',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create($nextyear, '07', '31')->format('Y-m-d')],
            ['Netherlands Antilles','AN',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create( $nextyear, '07', '31')->format('Y-m-d')],
            ['New Caledonia','NC',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create( $nextyear, '07', '31')->format('Y-m-d')],
            ['New Zealand','NZ',Carbon::create( $year, '01', '01')->format('Y-m-d'),Carbon::create( $year, '12', '31')->format('Y-m-d')],
            ['Nicaragua','NI',Carbon::create( $year, '01', '01')->format('Y-m-d'),Carbon::create( $year, '12', '31')->format('Y-m-d')],
            ['Niger','NE',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create( $nextyear, '07', '31')->format('Y-m-d')],
            ['Nigeria','NG',Carbon::create( $year, '01', '01')->format('Y-m-d'),Carbon::create( $year, '12', '31')->format('Y-m-d')],
            ['Niue','NU',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create( $nextyear, '07', '31')->format('Y-m-d')],
            ['Norfolk Island','NF',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create( $nextyear, '07', '31')->format('Y-m-d')],
            ['Northern Mariana Islands','MP',Carbon::create( $year, '01', '01')->format('Y-m-d'),Carbon::create( $year, '12', '31')->format('Y-m-d')],
            ['Norway','NO',Carbon::create( $year, '01', '01')->format('Y-m-d'),Carbon::create( $year, '12', '31')->format('Y-m-d')],
            ['Palestine','PS',Carbon::create( $year, '01', '01')->format('Y-m-d'),Carbon::create( $year, '12', '31')->format('Y-m-d')],
            ['Oman','OM',Carbon::create( $year, '01', '01')->format('Y-m-d'),Carbon::create( $year, '12', '31')->format('Y-m-d')],
            ['Pakistan','PK',Carbon::create( $year, '04', '01')->format('Y-m-d'),Carbon::create( $nextyear, '03', '31')->format('Y-m-d')],
            ['Palau','PW',Carbon::create( $year, '01', '01')->format('Y-m-d'),Carbon::create( $year, '12', '31')->format('Y-m-d')],
            ['Panama','PA',Carbon::create( $year, '01', '01')->format('Y-m-d'),Carbon::create( $year, '12', '31')->format('Y-m-d')],
            ['Papua New Guinea','PG',Carbon::create( $year, '01', '01')->format('Y-m-d'),Carbon::create( $year, '12', '31')->format('Y-m-d')],
            ['Paraguay','PY',Carbon::create( $year, '01', '01')->format('Y-m-d'),Carbon::create( $year, '12', '31')->format('Y-m-d')],
            ['Peru','PE',Carbon::create( $year, '01', '01')->format('Y-m-d'),Carbon::create( $year, '12', '31')->format('Y-m-d')],
            ['Philippines','PH',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create( $nextyear, '07', '31')->format('Y-m-d')],
            ['Pitcairn','PN',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create( $nextyear, '07', '31')->format('Y-m-d')],
            ['Poland','PL',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create( $nextyear, '07', '31')->format('Y-m-d')],
            ['Portugal','PT',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create($nextyear, '07', '31')->format('Y-m-d')],
            ['Puerto Rico','PR',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create( $nextyear, '07', '31')->format('Y-m-d')],
            ['Qatar','QA',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create($nextyear, '07', '31')->format('Y-m-d')],
            ['South Korea','KR',Carbon::create( $year, '01', '01')->format('Y-m-d'),Carbon::create( $year, '12', '31')->format('Y-m-d')],
            ['Moldova','MD',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create($nextyear, '07', '31')->format('Y-m-d')],
            ['Reunion','RE',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create( $nextyear, '07', '31')->format('Y-m-d')],
            ['Romania','RO',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create( $nextyear, '07', '31')->format('Y-m-d')],
            ['Russian Federation','RU',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create( $nextyear, '07', '31')->format('Y-m-d')],
            ['Rwanda','RW',Carbon::create( $year, '01', '01')->format('Y-m-d'),Carbon::create( $year, '12', '31')->format('Y-m-d')],
            ['Saint-Barthelemy','BL',Carbon::create( $year, '01', '01')->format('Y-m-d'),Carbon::create( $year, '12', '31')->format('Y-m-d')],
            ['Saint Helena','SH',Carbon::create( $year, '01', '01')->format('Y-m-d'),Carbon::create( $year, '12', '31')->format('Y-m-d')],
            ['Saint Kitts and Nevis','KN',Carbon::create( $year, '01', '01')->format('Y-m-d'),Carbon::create( $year, '12', '31')->format('Y-m-d')],
            ['Saint Lucia','LC',Carbon::create( $year, '01', '01')->format('Y-m-d'),Carbon::create( $year, '12', '31')->format('Y-m-d')],
            ['Saint-Martin','MF',Carbon::create( $year, '01', '01')->format('Y-m-d'),Carbon::create( $year, '12', '31')->format('Y-m-d')],
            ['Saint Pierre and Miquelon','PM',Carbon::create( $year, '01', '01')->format('Y-m-d'),Carbon::create( $year, '12', '31')->format('Y-m-d')],
            ['Saint Vincent and th Grenadines','VC',Carbon::create( $year, '01', '01')->format('Y-m-d'),Carbon::create( $year, '12', '31')->format('Y-m-d')],
            ['Samoa','WS',Carbon::create( $year, '01', '01')->format('Y-m-d'),Carbon::create( $year, '12', '31')->format('Y-m-d')],
            ['San Marino','SM',Carbon::create( $year, '01', '01')->format('Y-m-d'),Carbon::create( $year, '12', '31')->format('Y-m-d')],
            ['Sao Tome and Principe','ST',Carbon::create( $year, '01', '01')->format('Y-m-d'),Carbon::create( $year, '12', '31')->format('Y-m-d')],
            ['Saudi Arabia','SA',Carbon::create( $year, '01', '01')->format('Y-m-d'),Carbon::create( $year, '12', '31')->format('Y-m-d')],
            ['Senegal','SN',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create($nextyear, '07', '31')->format('Y-m-d')],
            ['Serbia','RS',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create( $nextyear, '07', '31')->format('Y-m-d')],
            ['Seychelles','SC',Carbon::create( $year, '01', '01')->format('Y-m-d'),Carbon::create( $year, '12', '31')->format('Y-m-d')],
            ['Sierra Leone','SL',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create( $nextyear, '07', '31')->format('Y-m-d')],
            ['Singapore','SG',Carbon::create( $year, '01', '01')->format('Y-m-d'),Carbon::create( $year, '12', '31')->format('Y-m-d')],
            ['Slovakia','SK',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create( $nextyear, '07', '31')->format('Y-m-d')],
            ['Slovenia','SI',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create($nextyear, '07', '31')->format('Y-m-d')],
            ['Solomon Islands','SB',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create( $nextyear, '07', '31')->format('Y-m-d')],
            ['Somalia','SO',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create( $nextyear, '07', '31')->format('Y-m-d')],
            ['South Africa','ZA',Carbon::create( $year, '01', '01')->format('Y-m-d'),Carbon::create( $year, '12', '31')->format('Y-m-d')],
            ['Spain','ES',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create( $nextyear, '07', '31')->format('Y-m-d')],
            ['Sri Lanka','LK',Carbon::create( $year, '01', '01')->format('Y-m-d'),Carbon::create($year, '12', '31')->format('Y-m-d')],
            ['Sudan','SD',Carbon::create( $year, '01', '01')->format('Y-m-d'),Carbon::create( $year, '12', '31')->format('Y-m-d')],
            ['Suriname','SR',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create($nextyear, '07', '31')->format('Y-m-d')],
            ['Svalbard and Jan Maye Islands','SJ',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create( $nextyear, '07', '31')->format('Y-m-d')],
            ['Swaziland','SZ',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create( $nextyear, '07', '31')->format('Y-m-d')],
            ['Sweden','SE',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create( $nextyear, '07', '31')->format('Y-m-d')],
            ['Switzerland','CH',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create( $nextyear, '07', '31')->format('Y-m-d')],
            ['Syrian Arab Republic','SY',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create( $nextyear, '07', '31')->format('Y-m-d')],
            ['Tajikistan','TJ',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create($nextyear, '07', '31')->format('Y-m-d')],
            ['Thailand','TH',Carbon::create( $year, '04', '01')->format('Y-m-d'),Carbon::create( $nextyear, '03', '31')->format('Y-m-d')],
            ['Macedonia','MK',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create( $nextyear, '07', '31')->format('Y-m-d')],
            ['Timor-Leste','TP',Carbon::create( $year, '01', '01')->format('Y-m-d'),Carbon::create( $year, '12', '31')->format('Y-m-d')],
            ['Togo','TG',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create( $nextyear, '07', '31')->format('Y-m-d')],
            ['Tokelau','TK',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create( $nextyear, '07', '31')->format('Y-m-d')],
            ['Tonga','TO',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create( $nextyear, '07', '31')->format('Y-m-d')],
            ['Trinidad and Tobago','TT',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create( $nextyear, '07', '31')->format('Y-m-d')],
            ['Tunisia','TN',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create( $nextyear, '07', '31')->format('Y-m-d')],
            ['Turkey','TR',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create( $nextyear, '07', '31')->format('Y-m-d')],
            ['Turkmenistan','TM',Carbon::create( $year, '01', '01')->format('Y-m-d'),Carbon::create( $year, '12', '31')->format('Y-m-d')],
            ['Turks and Caicos Islands','TC',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create( $nextyear, '07', '31')->format('Y-m-d')],
            ['Tuvalu','TV',Carbon::create( $year, '01', '01')->format('Y-m-d'),Carbon::create( $year, '12', '31')->format('Y-m-d')],
            ['Uganda','UG',Carbon::create( $year, '01', '01')->format('Y-m-d'),Carbon::create( $year, '12', '31')->format('Y-m-d')],
            ['Ukraine','UA',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create( $nextyear, '07', '31')->format('Y-m-d')],
            ['United Arab Emirates','AE',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create($nextyear, '07', '31')->format('Y-m-d')],
            ['United Kingdom','UK',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create( $nextyear, '07', '31')->format('Y-m-d')],
            ['Tanzania','TZ',Carbon::create( $year, '04', '01')->format('Y-m-d'),Carbon::create( $nextyear, '03', '31')->format('Y-m-d')],
            ['United States','US',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create( $nextyear, '07', '31')->format('Y-m-d')],
            ['U.S. Virgin Islands','VI',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create( $nextyear, '07', '31')->format('Y-m-d')],
            ['Uruguay','UY',Carbon::create( $year, '01', '01')->format('Y-m-d'),Carbon::create( $year, '12', '31')->format('Y-m-d')],
            ['Uzbekistan','UZ',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create( $nextyear, '07', '31')->format('Y-m-d')],
            ['Vanuatu','VU',Carbon::create( $year, '01', '01')->format('Y-m-d'),Carbon::create( $year, '12', '31')->format('Y-m-d')],
            ['Venezuela','VE',Carbon::create( $year, '01', '01')->format('Y-m-d'),Carbon::create( $year, '12', '31')->format('Y-m-d')],
            ['Viet Nam','VN',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create( $nextyear, '07', '31')->format('Y-m-d')],
            ['Wallis and Futuna Islands','WF',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create($nextyear, '07', '31')->format('Y-m-d')],
            ['Western Sahara','EH',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create($nextyear, '07', '31')->format('Y-m-d')],
            ['Yemen','YE',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create( $nextyear, '07', '31')->format('Y-m-d')],
            ['Zambia','ZM',Carbon::create( $year, '01', '01')->format('Y-m-d'),Carbon::create( $year, '12', '31')->format('Y-m-d')],
            ['Zimbabwe','ZW',Carbon::create( $year, '01', '01')->format('Y-m-d'),Carbon::create( $year, '12', '31')->format('Y-m-d')],
            ['South Sudan','SS',Carbon::create( $year, '08', '01')->format('Y-m-d'),Carbon::create( $nextyear, '07', '31')->format('Y-m-d')],
        ];
        foreach ($array as $key => $value):
            $array2[] = [
                'country'  => $value[0],
                'start_date' => $value[2],
                'end_date' => $value[3],
                'created_at' => Carbon::now()->toDateTimeString(),
                'updated_at' => Carbon::now()->toDateTimeString(),
            ];
            endforeach ;

            DB::table('countries')->insert($array2);
    }
}